# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsDDtXPLV6LUxZ3u2NEgfjHIK_v56XLV
"""

import os

def load_data():
    """
    vzhou842'nin örnek veri setini kullanır.
    veri biçimi: [(label, metin)]
    """
    dataset = []
    with open("scratch_rnn/sentiment.txt", encoding="utf-8") as f:
        for line in f:
            label, sentence = line.strip().split('\t')
            dataset.append((int(label), sentence))
    return dataset

