# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWdjnJVjCc2CGQiR88eH2vKx-T7Umwq_
"""

from data import load_data
from model import RNN
from utils import tokenize, build_vocab, encode_sentence, evaluate
import numpy as np

data = load_data()
sentences = [s for _, s in data]
labels = [l for l, _ in data]

tokenized = [tokenize(s) for s in sentences]
vocab = build_vocab(tokenized)
encoded = [encode_sentence(s, vocab) for s in tokenized]

# Eğitim-veri ayrımı
train_X, train_y = encoded[:80], labels[:80]
test_X, test_y = encoded[80:], labels[80:]

rnn = RNN(len(vocab))
correct = 0
for epoch in range(10):
    for i in range(len(train_X)):
        pred = rnn.predict(train_X[i])
        if pred == train_y[i]:
            correct += 1
    print(f"Epoch {epoch+1} accuracy: {correct / len(train_X):.2f}")
    correct = 0

# Test doğruluğu
accuracy = evaluate(rnn, test_X, test_y)
print("Test accuracy:", accuracy)

