# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWdjnJVjCc2CGQiR88eH2vKx-T7Umwq_
"""

def tokenize(sentence):
    return sentence.lower().split()

def build_vocab(tokenized_sentences):
    vocab = {}
    idx = 0
    for sentence in tokenized_sentences:
        for word in sentence:
            if word not in vocab:
                vocab[word] = idx
                idx += 1
    return vocab

def encode_sentence(tokens, vocab):
    return [vocab[word] for word in tokens if word in vocab]

def evaluate(model, X, y):
    correct = sum(model.predict(x) == y[i] for i, x in enumerate(X))
    return correct / len(X)

